<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-15T11:19:59 CST" name="Tercera-Entrega-Suit" finished-at="2021-08-15T11:20:00 CST" duration-ms="770">
    <groups>
      <group name="unitTest">
        <method signature="UnitTesting.agregarCliente()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" name="agregarCliente" class="UnitTesting.UnitTesting"/>
        <method signature="UnitTesting.gettersYsettersInventario()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" name="gettersYsettersInventario" class="UnitTesting.UnitTesting"/>
        <method signature="UnitTesting.gettersYsettersPedidos()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" name="gettersYsettersPedidos" class="UnitTesting.UnitTesting"/>
      </group> <!-- unitTest -->
    </groups>
    <test started-at="2021-08-15T11:19:59 CST" name="unitTest" finished-at="2021-08-15T11:20:00 CST" duration-ms="770">
      <class name="UnitTesting.UnitTesting">
        <test-method signature="agregarCliente()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" started-at="2021-08-15T11:19:59 CST" name="agregarCliente" description="Prueba agregar nuevo Cliente" finished-at="2021-08-15T11:20:00 CST" duration-ms="670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- agregarCliente -->
        <test-method signature="gettersYsettersInventario()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" started-at="2021-08-15T11:20:00 CST" name="gettersYsettersInventario" description="Prueba métodos getter y setter de Inventario" finished-at="2021-08-15T11:20:00 CST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error getters y setter Inventario
expected [21] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error getters y setter Inventario
expected [21] but found [20]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at UnitTesting.UnitTesting.gettersYsettersInventario(UnitTesting.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettersYsettersInventario -->
        <test-method signature="gettersYsettersPedidos()[pri:0, instance:UnitTesting.UnitTesting@2ed0fbae]" started-at="2021-08-15T11:20:00 CST" name="gettersYsettersPedidos" description="Prueba métodos getter y setter de Pedidos" finished-at="2021-08-15T11:20:00 CST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettersYsettersPedidos -->
      </class> <!-- UnitTesting.UnitTesting -->
    </test> <!-- unitTest -->
  </suite> <!-- Tercera-Entrega-Suit -->
</testng-results>
